// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Previewer: typeof import('./src/components/previewer/index.vue')['default']
    TextArea: typeof import('./src/components/textArea/index.vue')['default']
  }
}
